project:
  name: vpc-test
  parameters:
    AvailabilityZone1: us-east-1a
    AvailabilityZone2: us-east-1b
    EnvironmentName: TestEnv
    PrivateSubnetCIDR1: 10.0.3.0/24
    PrivateSubnetCIDR2: 10.0.4.0/24
    PublicSubnetCIDR1: 10.0.1.0/24
    PublicSubnetCIDR2: 10.0.2.0/24
    VpcCIDR: 10.0.0.0/16
  region: us-east-1

regions:
  us-east-1:
    stacks:
      - VPCStack

stacks:
  VPCStack:
    parameters:
      AvailabilityZone1: us-east-1a  # Truyền trực tiếp giá trị
      AvailabilityZone2: us-east-1b  # Truyền trực tiếp giá trị
      EnvironmentName: TestEnv  # Truyền trực tiếp giá trị
      PrivateSubnetCIDR1: 10.0.3.0/24  # Truyền trực tiếp giá trị
      PrivateSubnetCIDR2: 10.0.4.0/24  # Truyền trực tiếp giá trị
      PublicSubnetCIDR1: 10.0.1.0/24  # Truyền trực tiếp giá trị
      PublicSubnetCIDR2: 10.0.2.0/24  # Truyền trực tiếp giá trị
      VpcCIDR: 10.0.0.0/16  # Truyền trực tiếp giá trị
    template: vpc.yml

tests:
  basic:
    regions:
      - us-east-1
    stacks:
      - VPCStack
