project:
  name: security-groups-test
  parameters:
    EnvironmentName: TestEnv
    VpcId: vpc-12345678  # Thay thế bằng VPC ID của bạn
    AllowedSSHIP: 192.168.86.1/32  # CIDR block cho SSH access

regions:
  us-east-1:
    stacks:
      - SecurityGroupsStack

stacks:
  SecurityGroupsStack:
    parameters:
      EnvironmentName: ${EnvironmentName}  # Sử dụng tham số từ project
      VpcId: ${VpcId}  # Sử dụng tham số từ project
      AllowedSSHIP: ${AllowedSSHIP}  # Sử dụng tham số từ project
    template: security_groups.yml  # Tên tệp template của bạn

tests:
  basic:
    regions:
      - us-east-1
    stacks:
      - SecurityGroupsStack
